version: '2'

services:
    mysql:
        image: mysql:latest
        environment:
          - MYSQL_ROOT_PASSWORD=secret
          - MYSQL_USER=root
          - MYSQL_PASSWORD=secret
        volumes:
          - ./mysql:/var/lib/mysql
        ports:
          - 3306:3306

    server:
        build: ./server
        image: server:v1.0
        volumes:
          - ./projects/:/var/www
        ports:
          - 80:80
          - 443:443
        depends_on:
          - mysql

    mongo:
        image: mongo:3.0.4
        volumes:
          - ./mongo:/data/db
        ports:
          - "27017:27017"
        command: --smallfiles --rest

    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        links:
            - mysql
        environment:
            PMA_HOST: mysql
        volumes:
            - ./pma/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
